export const categories = [
    "Adventure stories",
    "Art & Photography",
    "Biographies",
    "Children & Young Adult Reading",
    "Classics of Literature",
    "Computers & Technology",
    "Drama",
    "Fiction",
    "Health/Fitness",
    "History",
    "Humor",
    "Law",
    "Literature",
    "Music",
    "Nature",
    "Poetry",
    "Reference",
    "Religion/Spirituality",
    "Science",
    "Short Stories",
    "Travel Writing",
];